name: Build Linux

on:
  push:
    branches:
    - release/production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Install Snapcraft
      uses: samuelmeuli/action-snapcraft@v1
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v1
      with:
        node-version: 20.x

    - name: install dependencies
      run: npm i

    - name: build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      run: npm run build:linux -- --publish never

    - name: publish amd64
      uses: snapcore/action-publish@v1
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_EXPORT }}
      with:
        snap: "${{ github.workspace }}/dist/Raindrop-amd64.snap"
        release: stable